# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'W&F' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for W&F

pod 'Alamofire'

pod 'SwiftKeychainWrapper'

pod 'SDWebImage'

end
